Repository provenance-io/provenance, pull requests merged in 2021-08, with the labels that each got.

#407 Verify secp256r1 key support
  x/marker/handler_test.go
  x/metadata/handler_test.go
  x/name/handler_test.go
  x/name/keeper/keeper_test.go
Labels: enhancement, security

#421 Update to final Cosmos SDK 0.43
  app/app.go
  go.mod
  go.sum
Labels: dependencies

#430 Validate marker access by type
  CHANGELOG.md
  client/docs/statik/statik.go
  client/docs/swagger-ui/swagger.yaml
  proto/provenance/marker/v1/accessgrant.proto
  x/marker/keeper/migrations.go
  x/marker/legacy/v042/store.go
  x/marker/legacy/v042/store_test.go
  x/marker/legacy/v042/types.go
  x/marker/simulation/operations.go
  x/marker/types/accessgrant.go
  x/marker/types/accessgrant_test.go
  x/marker/types/marker.go
  x/marker/types/marker_test.go
Labels: bug, marker

#458 Add setting of home path to createAppAndExport app setup
  CHANGELOG.md
  cmd/provenanced/cmd/root.go
Labels: bug, wasm

#405 Update init cmd defaults and create config cmd
  .gitignore
  CHANGELOG.md
  app/app.go
  cmd/provenanced/cmd/clientconfig.go
  cmd/provenanced/cmd/clientconfig_test.go
  cmd/provenanced/cmd/config.go
  cmd/provenanced/cmd/config_test.go
  cmd/provenanced/cmd/init.go
  cmd/provenanced/cmd/root.go
  cmd/provenanced/cmd/testnet.go
  cmd/provenanced/config/client.go
  cmd/provenanced/config/filenames.go
  cmd/provenanced/config/interceptor.go
  cmd/provenanced/config/manager.go
  cmd/provenanced/config/manager_test.go
  cmd/provenanced/config/reflector.go
  cmd/provenanced/config/reflector_test.go
  cmd/provenanced/config/server.go
  cmd/provenanced/config/toml.go
  x/marker/spec/09_params.md
  x/marker/types/si.go
Labels: CLI
