Repository provenance-io/provenance, pull requests merged in 2022-08, with the labels that each got.

#911 Update metadata module to properly manage authz grants.
  CHANGELOG.md
  go.mod
  go.sum
  third_party/proto/cosmos/authz/v1beta1/authz.proto
  x/metadata/client/cli/cli_test.go
  x/metadata/keeper/keeper.go
  x/metadata/keeper/keeper_test.go
  x/metadata/keeper/scope.go
Labels: authz

#1003 Add support for psql indexing
  CHANGELOG.md
  Makefile
  docker/postgres-indexer/Dockerfile
  docker/postgres-indexer/README.md
  docker/postgres-indexer/db-init/tendermint.sql
  docker/postgres-indexer/docker-compose.yaml
Labels: enhancement

#1021 Fix minimum fee charging for successful tx to sweep remainder of base fee
  CHANGELOG.md
  app/test_helpers.go
  internal/antewrapper/prov_fee_test.go
  internal/antewrapper/prov_feegrant_test.go
  internal/antewrapper/provenance_fee.go
  internal/antewrapper/testutil_test.go
  internal/handlers/msg_fee_invoker.go
  internal/handlers/msg_fee_invoker_test.go
  internal/handlers/msg_service_router_test.go
  x/name/handler_test.go
Labels: bug, msgfees
